version: "3"
services:
  wdio-cucumber:
    build: .
    image: wdio-cucumber
    container_name: wdio-cucumber
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    expose:
      - "4444"
